// apps/khaos/src/app/shared/form/select/simple-select.tsx
import { SelectElement } from './type/SelectElement';

interface SimpleSelectProps {
  elements: SelectElement[];
  onChange: (value: string) => void;
  selected?: string;
}

function SimpleSelect({ elements, onChange, selected }: SimpleSelectProps) {
  return (
    <select
      className="w-full rounded-md border bg-background px-3 py-2 bg-white"
      onChange={e => onChange(e.target.value)}
      value={selected}
    >
      {elements.map(element => <option key={element.value} value={element.value}>{element.name}</option>)}
    </select>
  );
}

export default SimpleSelect;

// apps/sandbox-web-app/src/app/shared/input/simple-select/simple-select.component.ts
import {AfterViewInit, Component, input, OnInit, output, signal} from '@angular/core';
import {FormsModule, ReactiveFormsModule} from "@angular/forms";

@Component({
  selector: 'app-simple-select',
  imports: [
    ReactiveFormsModule,
    FormsModule
  ],
  templateUrl: './simple-select.component.html',
  styleUrl: './simple-select.component.css',
})
export class SimpleSelect implements AfterViewInit {
  elements = input<string[]>([]);
  selected = input<string>("");
  change = output<string>();

  value = signal<string>('');


  ngAfterViewInit() {
    this.value.set(this.selected());
  }

  onChange(event: Event) {
    const selectedValue = (event.target as HTMLSelectElement).value;
    this.value.set(selectedValue);
    this.change.emit(selectedValue);
  }
}

<select
  class="w-full rounded-md border px-3 py-2 bg-white"
  [(ngModel)]="value"
  (change)="onChange($event)"
>
  @for (element of elements(); track element) {
    <option [value]="element">{{ element }}</option>
  }
</select>
